### ISSUE TITLE
chsmack 1.1: add a recursive behaviour

### ISSUE THREAD

**Issue by jobol** [smack-team/smack#103]
Add an option to apply change to all files of subtrees, descending the subtree hierarchy
I currently use the utility `find` but an option could be good.

**Comment by ravizombie** [comment]
am thinking of extending it to have the recursive option.  how did you use it currently ?

**Comment by jobol** [comment]
Great news! Implementing an option would be easier in some case than

    find . -type f -exec chsmack -a User {} \;

or 

    find . -type f | xargs -n 1 chsmack -a User

or 

    chsmack -a User $(find . -type f)

**Comment by rafal-krypa** [comment]
A pull request would be welcome. As @jobol wrote, there are several ways around the lack of option. But several analogous tools handle "-r" option and chsmack could too.
