### ISSUE TITLE
chsmack can't remove labels

### ISSUE THREAD

**Issue by jobol** [smack-team/smack#28]
It seems to me that I can't remove the labels put with chsmack. 

(nota, I tried to set an empty string but the logic of chsmack doesn't handle it: it ignore the otpion)

**Comment by Jurij0110** [comment]
Hello @jarkkojs and @jobol 
Currently, I also have a problem with delete the SMACK labels

https://github.com/smack-team/smack/issues/139
Could you please help me take a look at this issue

Thank you so much
